name: isolation
description: Isolate helper for flutter and dart.
version: 0.0.1-dev
repository: https://github.com/PlugFox/isolation
issue_tracker: https://github.com/PlugFox/isolation/issues
homepage: https://github.com/PlugFox/isolation

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.0
