name: isolation
description: |
  The library allows you to simplify the creation and interaction of isolates for dart and flutter.
  The interaction between isolates is an interface similar to stream controllers.
version: 0.0.2-dev
repository: https://github.com/PlugFox/isolation
issue_tracker: https://github.com/PlugFox/isolation/issues
homepage: https://github.com/PlugFox/isolation

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  meta: ^1.7.0

dev_dependencies:
  test: ^1.16.0
  coverage: any
